# Generated by Django 5.0 on 2024-03-21 14:54

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='photo/', verbose_name='Фотография'),
        ),
    ]
