# Generated by Django 5.0 on 2024-03-19 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_number', models.CharField(max_length=16, verbose_name='Номер телефона')),
                ('second_number', models.CharField(max_length=16, verbose_name='Второй номер')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Введите почту')),
                ('work_time', models.CharField(max_length=100, verbose_name='Время работы по будням')),
                ('work_time_ru', models.CharField(max_length=100, null=True, verbose_name='Время работы по будням')),
                ('work_time_ky', models.CharField(max_length=100, null=True, verbose_name='Время работы по будням')),
                ('holiday_work_time', models.CharField(max_length=100, verbose_name='В выходные и праздничные дни')),
                ('holiday_work_time_ru', models.CharField(max_length=100, null=True, verbose_name='В выходные и праздничные дни')),
                ('holiday_work_time_ky', models.CharField(max_length=100, null=True, verbose_name='В выходные и праздничные дни')),
                ('address', models.CharField(max_length=150, verbose_name='Адрес')),
                ('address_ru', models.CharField(max_length=150, null=True, verbose_name='Адрес')),
                ('address_ky', models.CharField(max_length=150, null=True, verbose_name='Адрес')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Введите ссылку')),
            ],
            options={
                'verbose_name': ('Контакт',),
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
