# Generated by Django 5.0 on 2024-03-19 07:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Текст')),
                ('text_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Текст')),
                ('text_ky', ckeditor.fields.RichTextField(null=True, verbose_name='Текст')),
                ('add_text', ckeditor.fields.RichTextField(verbose_name='Доп. Текст')),
                ('add_text_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Доп. Текст')),
                ('add_text_ky', ckeditor.fields.RichTextField(null=True, verbose_name='Доп. Текст')),
            ],
            options={
                'verbose_name': ('О нас',),
                'verbose_name_plural': 'О нас',
            },
        ),
    ]
