# Generated by Django 5.0 on 2024-03-19 07:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abonement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=50, null=True, verbose_name='Название')),
                ('title_ky', models.CharField(max_length=50, null=True, verbose_name='Название')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('description_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('description_ky', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('time', models.CharField(max_length=150, verbose_name='Время посещения')),
                ('time_ru', models.CharField(max_length=150, null=True, verbose_name='Время посещения')),
                ('time_ky', models.CharField(max_length=150, null=True, verbose_name='Время посещения')),
                ('price', models.CharField(max_length=20, verbose_name='Стоимость')),
                ('price_ru', models.CharField(max_length=20, null=True, verbose_name='Стоимость')),
                ('price_ky', models.CharField(max_length=20, null=True, verbose_name='Стоимость')),
                ('special', models.BooleanField(verbose_name='Специальное предложение?')),
            ],
            options={
                'verbose_name': ('Абонемент',),
                'verbose_name_plural': 'Абонементы',
            },
        ),
    ]
