# Generated by Django 5.0 on 2024-03-19 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('price', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цена')),
                ('photo', models.ImageField(choices=[('icon1', 'Icon 1'), ('icon2', 'Icon 2')], upload_to='icons/', verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
